# Generated by Django 4.2.6 on 2024-07-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency_preference',
            field=models.CharField(choices=[('BGN', 'BGN'), ('EUR', 'EUR')], default='BGN', max_length=3),
        ),
    ]
