version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

    env_file:
      - .env.prod
    depends_on:
      - postgres
      - pgadmin4
      - backend
    networks:
      - cardflow
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "5173:5173"
    expose:
      - "5173"
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - .env.prod
    depends_on:
      - postgres
      - pgadmin4
    networks:
      - cardflow
    volumes:
      - ./backend:/usr/src/app
      - ./backend/static_files:/usr/src/app/static_files
      - ./backend/media:/usr/src/app/media

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env.prod
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - cardflow


  pgadmin4:
    image: dpage/pgadmin4
    user: "${UID}:${GID}" # to avoid permission issues
    env_file:
      - ./.env.prod
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    ports:
      - "5433:81"
    depends_on:
      - postgres
    networks:
      - cardflow

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
      - ./backend/media:/usr/share/nginx/media
      - ./backend/static_files:/usr/share/nginx/static_files/
      - /etc/letsencrypt/live/cardflow.market/fullchain.pem:/etc/letsencrypt/live/cardflow.market/fullchain.pem
      - /etc/letsencrypt/live/cardflow.market/privkey.pem:/etc/letsencrypt/live/cardflow.market/privkey.pem
    depends_on:
      - frontend
      - backend
    networks:
      - cardflow

networks:
  cardflow:
    driver: bridge