# Generated by Django 4.2.6 on 2024-01-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='orders',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='orders',
            field=models.ManyToManyField(to='order.order'),
        ),
    ]
