# Generated by Django 4.2.6 on 2024-01-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_shoppingcart_order_shoppingcartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
