# Generated by Django 4.2.6 on 2024-01-22 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_shoppingcartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name=django.core.validators.MinValueValidator(1)),
        ),
    ]
