export const toastMessages = {
  // success
  login: 'login',
  register: 'register',
  logout: 'logout',
  emailSent: 'emailSent',
  usernameChanged: 'usernameChanged',
  emailChanged: 'emailChanged',
  avatarChanged: 'avatarChanged',
  shipmentAddressChanged: 'shipmentAddressChanged',
  currencyChanged: 'currencyChanged',
  accountDeleted: 'accountDeleted',
  shoppingCartItemDeleted: 'shoppingCartItemDeleted',
  shoppingCartEmptiedOut: 'shoppingCartEmptiedOut',
  shoppingCartItemAdded: 'shoppingCartItemAdded',
  checkout: 'checkout',
  listingUpdated: 'listingUpdated',
  listingVisibilityChanged: 'listingVisibilityChanged',
  listingDeleted: 'listingDeleted',
  listingCreated: 'listingCreated',
  listingEdited: 'listingEdited',
  sellListingsDelisted: 'sellListingsDelisted',
  sellListingsDeleted: 'sellListingsDeleted',
  sellListingsListed: 'sellListingsListed',
  sellListingListed: 'sellListingListed',
  sellListingDelisted: 'sellListingDelisted',
  orderStatusChanged: 'orderStatusChanged',
  feedbackGiven: 'feedbackGiven',

  // error
  serverError: 'serverError',
  notLoggedIn: 'notLoggedIn',
  noPermission: 'noPermission',
  pageDoesNotExist: 'pageDoesNotExist',
  failedLogin: 'failedLogin',
  failedShoppingCartQuantityUpdate: 'failedShoppingCartQuantityUpdate',
};
