# Generated by Django 4.2.6 on 2024-02-26 10:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAndRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('given_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_from', to=settings.AUTH_USER_MODEL)),
                ('given_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_to', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
