# Generated by Django 4.2.6 on 2024-02-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackandrating',
            old_name='receiver_user',
            new_name='receiver_user',
        ),
        migrations.RenameField(
            model_name='feedbackandrating',
            old_name='sender_user',
            new_name='sender_user',
        ),
    ]
