# Generated by Django 4.2.6 on 2024-02-29 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_rename_given_to_feedbackandrating_receiver_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackandrating',
            name='receiver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiveruser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbackandrating',
            name='sender_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
