# Generated by Django 4.2.6 on 2024-02-27 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_feedbackandrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackandrating',
            name='related_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order', to='order.order'),
        ),
    ]
