# Generated by Django 4.2.6 on 2024-06-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('not_sent', 'Not Sent'), ('not_received', 'Not Received'), ('sent', 'Sent'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=12),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(max_length=12),
        ),
    ]
