# Generated by Django 4.2.6 on 2024-07-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status_alter_orderstatushistory_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Order Status History'},
        ),
    ]
