# Generated by Django 4.2.6 on 2023-11-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YugiohCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yugioh_card_name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('frame_type', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('attack', models.CharField(blank=True, max_length=100, null=True)),
                ('defense', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('race', models.CharField(max_length=100)),
                ('attribute', models.CharField(blank=True, max_length=100, null=True)),
                ('archetype', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card')),
            ],
        ),
    ]
