# Generated by Django 4.2.6 on 2023-11-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yugiohcardset',
            name='card_set_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='yugiohcardset',
            name='set_code',
            field=models.CharField(max_length=100),
        ),
    ]
