# Generated by Django 4.2.6 on 2023-11-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yugiohcardset',
            old_name='rarity_code',
            new_name='set_code',
        ),
    ]
