# Generated by Django 4.2.6 on 2023-11-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yugiohcardinset', '0003_alter_yugiohcardinset_set'),
        ('yugioh', '0002_remove_yugiohcard_yugioh_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='yugiohcard',
            name='card_in_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yugiohcardinset.yugiohcardinset'),
            preserve_default=False,
        ),
    ]
