# Generated by Django 4.2.6 on 2023-11-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yugiohcardinset', '0003_alter_yugiohcardinset_set'),
        ('yugioh', '0003_yugiohcard_card_in_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yugiohcard',
            name='card_in_set',
        ),
        migrations.CreateModel(
            name='YugiohCardYugiohCardInSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yugioh_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugioh.yugiohcard')),
                ('yugioh_card_in_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugiohcardinset.yugiohcardinset')),
            ],
        ),
    ]
