# Generated by Django 4.2.6 on 2023-11-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yugiohcardset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yugiohcardset',
            name='card_in_set',
        ),
    ]
