# Generated by Django 4.2.6 on 2023-11-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yugiohcardinset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YugiohCardRarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(max_length=100, unique=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugiohcardinset.yugiohcardinset')),
            ],
        ),
    ]
