# Generated by Django 4.2.6 on 2023-11-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yugiohcardrarity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yugiohcardrarity',
            options={'ordering': ('set', 'rarity'), 'verbose_name': 'Yugioh Card Rarity', 'verbose_name_plural': 'Yugioh Card Rarities'},
        ),
    ]
