# Generated by Django 4.2.6 on 2023-11-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yugiohcardrarity', '0002_alter_yugiohcardrarity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yugiohcardrarity',
            options={'verbose_name': 'Yugioh Card Rarity', 'verbose_name_plural': 'Yugioh Card Rarities'},
        ),
        migrations.RemoveField(
            model_name='yugiohcardrarity',
            name='set',
        ),
    ]
