# Generated by Django 4.2.6 on 2023-11-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugiohcardrarity', '0003_alter_yugiohcardrarity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yugiohcardrarity',
            name='rarity_code',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
