# Generated by Django 4.2.6 on 2023-11-30 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yugioh', '0002_alter_yugiohcardset_card_set_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('condition', models.CharField(choices=[('poor', 'Poor'), ('played', 'Played'), ('good', 'Good'), ('excellent', 'Excellent'), ('near_mint', 'Near Mint'), ('mint', 'Mint')], max_length=9)),
                ('quantity', models.IntegerField()),
                ('is_listed', models.BooleanField(default=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugioh.yugiohcardinset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
