# Generated by Django 4.2.6 on 2024-07-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_tradable',
            field=models.BooleanField(default=False),
        ),
    ]
