# Generated by Django 4.2.6 on 2024-07-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_is_tradable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_tradable',
            new_name='is_trade_considered',
        ),
    ]
