# Generated by Django 4.2.6 on 2024-07-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_trade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
