# Generated by Django 4.2.6 on 2024-07-29 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0005_delete_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator_cash', models.FloatField(default=0.0)),
                ('recipient_cash', models.FloatField(default=0.0)),
                ('trade_status', models.CharField(choices=[('negotiate', 'Negotiate'), ('accept', 'Accept'), ('reject', 'Reject')], default='negotiate', max_length=9)),
                ('initiator_decision', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('recipient_decision', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_trades', to=settings.AUTH_USER_MODEL)),
                ('initiator_listing', models.ManyToManyField(related_name='initiated_trades', to='listing.listing')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trades', to=settings.AUTH_USER_MODEL)),
                ('recipient_listing', models.ManyToManyField(related_name='received_trades', to='listing.listing')),
            ],
        ),
    ]
