# Generated by Django 4.2.6 on 2024-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_status',
            field=models.CharField(choices=[('negotiate', 'Negotiate'), ('accept', 'Accept'), ('reject', 'Reject')], default='pending', max_length=9),
        ),
    ]
