# Generated by Django 4.2.6 on 2024-07-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_trade_trade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_status',
            field=models.CharField(choices=[('negotiate', 'Negotiate'), ('accept', 'Accept'), ('reject', 'Reject')], default='negotiate', max_length=9),
        ),
    ]
