# Generated by Django 4.2.6 on 2024-07-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_alter_trade_initiator_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='initiator_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('reject', 'Reject')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='trade',
            name='recipient_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('reject', 'Reject')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_status',
            field=models.CharField(choices=[('negotiate', 'Negotiate'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='negotiate', max_length=9),
        ),
    ]
