# Generated by Django 4.2.6 on 2023-11-01 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yugiohcardrarity', '0002_alter_yugiohcardrarity_options'),
        ('yugiohcardinset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yugiohcardinset',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugiohcardrarity.yugiohcardrarity'),
        ),
    ]
