# Generated by Django 4.2.6 on 2023-11-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yugiohcardset', '0002_remove_yugiohcardset_card_in_set'),
        ('yugiohcardinset', '0002_alter_yugiohcardinset_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yugiohcardinset',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugiohcardset.yugiohcardset'),
        ),
    ]
